name: CI/CD Pipeline for Server and Client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure deployment starts only after a successful build
    if: github.ref == 'refs/heads/master' # Deploys only when the master branch is updated

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.EXPANSE_TRACKER }} # Use the correct secret name
        run: |
          git remote add heroku https://git.heroku.com/expenses-tracker-api-v3.git || true  # Ignore if the remote already exists
          git push heroku master:master  # Push code to Heroku master branch, modify as necessary if Heroku uses main
