name: CI/CD Pipeline for Server and Client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for server
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/expense_tracker-server ./server
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/expense_tracker-server

      - name: Build and push Docker image for client
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/expense_tracker-client ./client
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/expense_tracker-client

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/expenses-tracker-api-v3.git || true
          git push heroku master:master
